// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pb/clientrpc/v1/rpc.proto

package clientrpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerConnState is possible connection states for a server.
type ServerConnState int32

const (
	// Do not use.
	ServerConnState_SERVER_CONN_STATE_UNSPECIFIED ServerConnState = 0
	// Closed.
	ServerConnState_SERVER_CONN_STATE_CLOSED ServerConnState = 1
	// Opening.
	ServerConnState_SERVER_CONN_STATE_OPENING ServerConnState = 2
	// Open.
	ServerConnState_SERVER_CONN_STATE_OPEN ServerConnState = 3
)

// Enum value maps for ServerConnState.
var (
	ServerConnState_name = map[int32]string{
		0: "SERVER_CONN_STATE_UNSPECIFIED",
		1: "SERVER_CONN_STATE_CLOSED",
		2: "SERVER_CONN_STATE_OPENING",
		3: "SERVER_CONN_STATE_OPEN",
	}
	ServerConnState_value = map[string]int32{
		"SERVER_CONN_STATE_UNSPECIFIED": 0,
		"SERVER_CONN_STATE_CLOSED":      1,
		"SERVER_CONN_STATE_OPENING":     2,
		"SERVER_CONN_STATE_OPEN":        3,
	}
)

func (x ServerConnState) Enum() *ServerConnState {
	p := new(ServerConnState)
	*p = x
	return p
}

func (x ServerConnState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerConnState) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_clientrpc_v1_rpc_proto_enumTypes[0].Descriptor()
}

func (ServerConnState) Type() protoreflect.EnumType {
	return &file_pb_clientrpc_v1_rpc_proto_enumTypes[0]
}

func (x ServerConnState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerConnState.Descriptor instead.
func (ServerConnState) EnumDescriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{0}
}

type Event_Type int32

const (
	// Do not use.
	Event_TYPE_UNSPECIFIED Event_Type = 0
	// A server's connection state changed.
	Event_TYPE_SERVER_CONN_STATE_CHANGE Event_Type = 1
	// A client went online.
	Event_TYPE_CLIENT_ONLINE Event_Type = 2
	// A client went offline.
	Event_TYPE_CLIENT_OFFLINE Event_Type = 3
)

// Enum value maps for Event_Type.
var (
	Event_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_SERVER_CONN_STATE_CHANGE",
		2: "TYPE_CLIENT_ONLINE",
		3: "TYPE_CLIENT_OFFLINE",
	}
	Event_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":              0,
		"TYPE_SERVER_CONN_STATE_CHANGE": 1,
		"TYPE_CLIENT_ONLINE":            2,
		"TYPE_CLIENT_OFFLINE":           3,
	}
)

func (x Event_Type) Enum() *Event_Type {
	p := new(Event_Type)
	*p = x
	return p
}

func (x Event_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_clientrpc_v1_rpc_proto_enumTypes[1].Descriptor()
}

func (Event_Type) Type() protoreflect.EnumType {
	return &file_pb_clientrpc_v1_rpc_proto_enumTypes[1]
}

func (x Event_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Type.Descriptor instead.
func (Event_Type) EnumDescriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{0, 0}
}

// Event is an event.
// Events are differentiated by type, and have different data based on that type.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event type.
	// The appropriate field will be filled based on the type.
	Type          Event_Type                   `protobuf:"varint,1,opt,name=type,proto3,enum=pb.clientrpc.v1.Event_Type" json:"type,omitempty"`
	ServerConn    *Event_ServerConnStateChange `protobuf:"bytes,2,opt,name=server_conn,json=serverConn,proto3,oneof" json:"server_conn,omitempty"`
	ClientOnline  *Event_ClientOnline          `protobuf:"bytes,3,opt,name=client_online,json=clientOnline,proto3,oneof" json:"client_online,omitempty"`
	ClientOffline *Event_ClientOffline         `protobuf:"bytes,4,opt,name=client_offline,json=clientOffline,proto3,oneof" json:"client_offline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetType() Event_Type {
	if x != nil {
		return x.Type
	}
	return Event_TYPE_UNSPECIFIED
}

func (x *Event) GetServerConn() *Event_ServerConnStateChange {
	if x != nil {
		return x.ServerConn
	}
	return nil
}

func (x *Event) GetClientOnline() *Event_ClientOnline {
	if x != nil {
		return x.ClientOnline
	}
	return nil
}

func (x *Event) GetClientOffline() *Event_ClientOffline {
	if x != nil {
		return x.ClientOffline
	}
	return nil
}

// EventContext is the context about where an event was generated.
type EventContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The UUID of the server where the event originated from.
	ServerUuid    string `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventContext) Reset() {
	*x = EventContext{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventContext) ProtoMessage() {}

func (x *EventContext) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventContext.ProtoReflect.Descriptor instead.
func (*EventContext) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *EventContext) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

// LogMessageAttr is an attribute within a LogMessage.
type LogMessageAttr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value kind.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// The key.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// The string representation of the value.
	// The value can be interpreted based on the value of `kind`.
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessageAttr) Reset() {
	*x = LogMessageAttr{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessageAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessageAttr) ProtoMessage() {}

func (x *LogMessageAttr) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessageAttr.ProtoReflect.Descriptor instead.
func (*LogMessageAttr) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *LogMessageAttr) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LogMessageAttr) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogMessageAttr) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// LogMessage is a structured log message.
type LogMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message's UID.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// The UNIX millisecond timestamp the log was sent on.
	CreatedTs int64 `protobuf:"varint,2,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	// The textual message.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// The message's attributes.
	Attrs         []*LogMessageAttr `protobuf:"bytes,4,rep,name=attrs,proto3" json:"attrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *LogMessage) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LogMessage) GetCreatedTs() int64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogMessage) GetAttrs() []*LogMessageAttr {
	if x != nil {
		return x.Attrs
	}
	return nil
}

// Information about a server.
type ServerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server's current state.
	State *ServerInfo_State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// The server's UUID.
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The name given to the server.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The server's address.
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	// The room to connect to.
	Room string `protobuf:"bytes,5,opt,name=room,proto3" json:"room,omitempty"`
	// The username to use for authentication.
	Username string `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	// The UNIX timestamp when the server was created.
	CreatedTs     int64 `protobuf:"varint,7,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *ServerInfo) GetState() *ServerInfo_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ServerInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServerInfo) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *ServerInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ServerInfo) GetCreatedTs() int64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

// Information about a server share.
type ShareInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The UUID of the associated server.
	ServerUuid string `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	// The share's name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The share's path on disk.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// The UNIX timestamp when the share was created.
	CreatedTs     int64 `protobuf:"varint,4,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareInfo) Reset() {
	*x = ShareInfo{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareInfo) ProtoMessage() {}

func (x *ShareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareInfo.ProtoReflect.Descriptor instead.
func (*ShareInfo) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *ShareInfo) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *ShareInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShareInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ShareInfo) GetCreatedTs() int64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

// OnlineUserInfo is information about an online user.
type OnlineUserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's username.
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineUserInfo) Reset() {
	*x = OnlineUserInfo{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUserInfo) ProtoMessage() {}

func (x *OnlineUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUserInfo.ProtoReflect.Descriptor instead.
func (*OnlineUserInfo) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *OnlineUserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// FileMeta is metadata about a file/folder.
type FileMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The file's name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether the file is a directory.
	IsDir bool `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	// The file's size, in bytes.
	// Always zero if the file is a folder.
	Size          uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMeta) Reset() {
	*x = FileMeta{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMeta) ProtoMessage() {}

func (x *FileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMeta.ProtoReflect.Descriptor instead.
func (*FileMeta) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *FileMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileMeta) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileMeta) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{8}
}

type StreamEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event.
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// The context about where the event was generated.
	Context       *EventContext `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsResponse) Reset() {
	*x = StreamEventsResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsResponse) ProtoMessage() {}

func (x *StreamEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamEventsResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *StreamEventsResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamEventsResponse) GetContext() *EventContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type StreamLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optionally, send existing logs after this timestamp before streaming live logs.
	// The timestamp is a UNIX millisecond timestamp.
	SendLogsAfterTs *int64 `protobuf:"varint,1,opt,name=send_logs_after_ts,json=sendLogsAfterTs,proto3,oneof" json:"send_logs_after_ts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *StreamLogsRequest) GetSendLogsAfterTs() int64 {
	if x != nil && x.SendLogsAfterTs != nil {
		return *x.SendLogsAfterTs
	}
	return 0
}

type StreamLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The logs.
	// This field usually has only one log message, but in the case of
	// sending back existing logs, it may have many.
	// The logs will be ordered by timestamp, ascending.
	Logs          []*LogMessage `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsResponse) Reset() {
	*x = StreamLogsResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsResponse) ProtoMessage() {}

func (x *StreamLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsResponse.ProtoReflect.Descriptor instead.
func (*StreamLogsResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *StreamLogsResponse) GetLogs() []*LogMessage {
	if x != nil {
		return x.Logs
	}
	return nil
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{12}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{13}
}

type GetClientInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientInfoRequest) Reset() {
	*x = GetClientInfoRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientInfoRequest) ProtoMessage() {}

func (x *GetClientInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientInfoRequest.ProtoReflect.Descriptor instead.
func (*GetClientInfoRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{14}
}

type GetClientInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The base URL to the HTTP file server.
	FileServerUrl string `protobuf:"bytes,1,opt,name=file_server_url,json=fileServerUrl,proto3" json:"file_server_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientInfoResponse) Reset() {
	*x = GetClientInfoResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientInfoResponse) ProtoMessage() {}

func (x *GetClientInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientInfoResponse.ProtoReflect.Descriptor instead.
func (*GetClientInfoResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *GetClientInfoResponse) GetFileServerUrl() string {
	if x != nil {
		return x.FileServerUrl
	}
	return ""
}

type GetServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServersRequest) Reset() {
	*x = GetServersRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServersRequest) ProtoMessage() {}

func (x *GetServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServersRequest.ProtoReflect.Descriptor instead.
func (*GetServersRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{16}
}

type GetServersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server records.
	Servers       []*ServerInfo `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServersResponse) Reset() {
	*x = GetServersResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServersResponse) ProtoMessage() {}

func (x *GetServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServersResponse.ProtoReflect.Descriptor instead.
func (*GetServersResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *GetServersResponse) GetServers() []*ServerInfo {
	if x != nil {
		return x.Servers
	}
	return nil
}

type CreateServerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name given to the server record.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The server's address.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// The room to connect to.
	Room string `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	// The username to use.
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	// The password to use.
	Password      string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerRequest) Reset() {
	*x = CreateServerRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerRequest) ProtoMessage() {}

func (x *CreateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerRequest.ProtoReflect.Descriptor instead.
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{18}
}

func (x *CreateServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateServerRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *CreateServerRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateServerRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateServerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created server record.
	Server        *ServerInfo `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerResponse) Reset() {
	*x = CreateServerResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerResponse) ProtoMessage() {}

func (x *CreateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerResponse.ProtoReflect.Descriptor instead.
func (*CreateServerResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{19}
}

func (x *CreateServerResponse) GetServer() *ServerInfo {
	if x != nil {
		return x.Server
	}
	return nil
}

type DeleteServerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server's UUID.
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerRequest) Reset() {
	*x = DeleteServerRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerRequest) ProtoMessage() {}

func (x *DeleteServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteServerRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerResponse) Reset() {
	*x = DeleteServerResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerResponse) ProtoMessage() {}

func (x *DeleteServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerResponse.ProtoReflect.Descriptor instead.
func (*DeleteServerResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{21}
}

type ConnectServerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server's UUID.
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectServerRequest) Reset() {
	*x = ConnectServerRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectServerRequest) ProtoMessage() {}

func (x *ConnectServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectServerRequest.ProtoReflect.Descriptor instead.
func (*ConnectServerRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{22}
}

func (x *ConnectServerRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ConnectServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectServerResponse) Reset() {
	*x = ConnectServerResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectServerResponse) ProtoMessage() {}

func (x *ConnectServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectServerResponse.ProtoReflect.Descriptor instead.
func (*ConnectServerResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{23}
}

type DisconnectServerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server's UUID.
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectServerRequest) Reset() {
	*x = DisconnectServerRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectServerRequest) ProtoMessage() {}

func (x *DisconnectServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectServerRequest.ProtoReflect.Descriptor instead.
func (*DisconnectServerRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{24}
}

func (x *DisconnectServerRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DisconnectServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectServerResponse) Reset() {
	*x = DisconnectServerResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectServerResponse) ProtoMessage() {}

func (x *DisconnectServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectServerResponse.ProtoReflect.Descriptor instead.
func (*DisconnectServerResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{25}
}

type UpdateServerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server's UUID.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The new name, if any.
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// The new address, if any.
	Address *string `protobuf:"bytes,3,opt,name=address,proto3,oneof" json:"address,omitempty"`
	// The new room, if any.
	Room *string `protobuf:"bytes,4,opt,name=room,proto3,oneof" json:"room,omitempty"`
	// The new username, if any.
	Username *string `protobuf:"bytes,5,opt,name=username,proto3,oneof" json:"username,omitempty"`
	// The new password, if any.
	Password      *string `protobuf:"bytes,6,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerRequest) Reset() {
	*x = UpdateServerRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerRequest) ProtoMessage() {}

func (x *UpdateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateServerRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateServerRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateServerRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *UpdateServerRequest) GetRoom() string {
	if x != nil && x.Room != nil {
		return *x.Room
	}
	return ""
}

func (x *UpdateServerRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateServerRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type UpdateServerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server after update.
	Server        *ServerInfo `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerResponse) Reset() {
	*x = UpdateServerResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerResponse) ProtoMessage() {}

func (x *UpdateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerResponse.ProtoReflect.Descriptor instead.
func (*UpdateServerResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateServerResponse) GetServer() *ServerInfo {
	if x != nil {
		return x.Server
	}
	return nil
}

type GetSharesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The UUID of the server to get shares for.
	ServerUuid    string `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSharesRequest) Reset() {
	*x = GetSharesRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSharesRequest) ProtoMessage() {}

func (x *GetSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSharesRequest.ProtoReflect.Descriptor instead.
func (*GetSharesRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{28}
}

func (x *GetSharesRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

type GetSharesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The shares.
	Shares        []*ShareInfo `protobuf:"bytes,1,rep,name=shares,proto3" json:"shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSharesResponse) Reset() {
	*x = GetSharesResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSharesResponse) ProtoMessage() {}

func (x *GetSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSharesResponse.ProtoReflect.Descriptor instead.
func (*GetSharesResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{29}
}

func (x *GetSharesResponse) GetShares() []*ShareInfo {
	if x != nil {
		return x.Shares
	}
	return nil
}

type CreateShareRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The UUID of the associated server.
	ServerUuid string `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	// The share's name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The share's path on disk.
	Path          string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShareRequest) Reset() {
	*x = CreateShareRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareRequest) ProtoMessage() {}

func (x *CreateShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareRequest.ProtoReflect.Descriptor instead.
func (*CreateShareRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{30}
}

func (x *CreateShareRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *CreateShareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateShareRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateShareResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created share.
	Share         *ShareInfo `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShareResponse) Reset() {
	*x = CreateShareResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareResponse) ProtoMessage() {}

func (x *CreateShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareResponse.ProtoReflect.Descriptor instead.
func (*CreateShareResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{31}
}

func (x *CreateShareResponse) GetShare() *ShareInfo {
	if x != nil {
		return x.Share
	}
	return nil
}

type DeleteShareRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The associated server UUID.
	ServerUuid string `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	// The share's name.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShareRequest) Reset() {
	*x = DeleteShareRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShareRequest) ProtoMessage() {}

func (x *DeleteShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShareRequest.ProtoReflect.Descriptor instead.
func (*DeleteShareRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteShareRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *DeleteShareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShareResponse) Reset() {
	*x = DeleteShareResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShareResponse) ProtoMessage() {}

func (x *DeleteShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShareResponse.ProtoReflect.Descriptor instead.
func (*DeleteShareResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{33}
}

type GetDirFilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server's UUID.
	ServerUuid string `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	// The online user's username.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// The path to get the contents of.
	Path          string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirFilesRequest) Reset() {
	*x = GetDirFilesRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirFilesRequest) ProtoMessage() {}

func (x *GetDirFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirFilesRequest.ProtoReflect.Descriptor instead.
func (*GetDirFilesRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{34}
}

func (x *GetDirFilesRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *GetDirFilesRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetDirFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetDirFilesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The directory's files.
	Content       []*FileMeta `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirFilesResponse) Reset() {
	*x = GetDirFilesResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirFilesResponse) ProtoMessage() {}

func (x *GetDirFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirFilesResponse.ProtoReflect.Descriptor instead.
func (*GetDirFilesResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{35}
}

func (x *GetDirFilesResponse) GetContent() []*FileMeta {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetFileMetaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server's UUID.
	ServerUuid string `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	// The online user's username.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// The path to get the contents of.
	Path          string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetaRequest) Reset() {
	*x = GetFileMetaRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetaRequest) ProtoMessage() {}

func (x *GetFileMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetaRequest.ProtoReflect.Descriptor instead.
func (*GetFileMetaRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{36}
}

func (x *GetFileMetaRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *GetFileMetaRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetFileMetaRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetFileMetaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The file's metadata.
	Meta          *FileMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetaResponse) Reset() {
	*x = GetFileMetaResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetaResponse) ProtoMessage() {}

func (x *GetFileMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetaResponse.ProtoReflect.Descriptor instead.
func (*GetFileMetaResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{37}
}

func (x *GetFileMetaResponse) GetMeta() *FileMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetOnlineUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server's UUID.
	ServerUuid    string `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineUsersRequest) Reset() {
	*x = GetOnlineUsersRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineUsersRequest) ProtoMessage() {}

func (x *GetOnlineUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineUsersRequest.ProtoReflect.Descriptor instead.
func (*GetOnlineUsersRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{38}
}

func (x *GetOnlineUsersRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

type GetOnlineUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The users.
	Users         []*OnlineUserInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineUsersResponse) Reset() {
	*x = GetOnlineUsersResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineUsersResponse) ProtoMessage() {}

func (x *GetOnlineUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineUsersResponse.ProtoReflect.Descriptor instead.
func (*GetOnlineUsersResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{39}
}

func (x *GetOnlineUsersResponse) GetUsers() []*OnlineUserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type ChangeAccountPasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server's UUID.
	ServerUuid string `protobuf:"bytes,1,opt,name=server_uuid,json=serverUuid,proto3" json:"server_uuid,omitempty"`
	// The account's current password.
	CurrentPassword string `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	// The account's new password.
	NewPassword   string `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeAccountPasswordRequest) Reset() {
	*x = ChangeAccountPasswordRequest{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeAccountPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAccountPasswordRequest) ProtoMessage() {}

func (x *ChangeAccountPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAccountPasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangeAccountPasswordRequest) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{40}
}

func (x *ChangeAccountPasswordRequest) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *ChangeAccountPasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangeAccountPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangeAccountPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeAccountPasswordResponse) Reset() {
	*x = ChangeAccountPasswordResponse{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeAccountPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAccountPasswordResponse) ProtoMessage() {}

func (x *ChangeAccountPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAccountPasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangeAccountPasswordResponse) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{41}
}

type Event_ServerConnStateChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server's new connection state.
	State         ServerConnState `protobuf:"varint,2,opt,name=state,proto3,enum=pb.clientrpc.v1.ServerConnState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_ServerConnStateChange) Reset() {
	*x = Event_ServerConnStateChange{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_ServerConnStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_ServerConnStateChange) ProtoMessage() {}

func (x *Event_ServerConnStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_ServerConnStateChange.ProtoReflect.Descriptor instead.
func (*Event_ServerConnStateChange) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Event_ServerConnStateChange) GetState() ServerConnState {
	if x != nil {
		return x.State
	}
	return ServerConnState_SERVER_CONN_STATE_UNSPECIFIED
}

type Event_ClientOnline struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The online user's info.
	Info          *OnlineUserInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_ClientOnline) Reset() {
	*x = Event_ClientOnline{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_ClientOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_ClientOnline) ProtoMessage() {}

func (x *Event_ClientOnline) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_ClientOnline.ProtoReflect.Descriptor instead.
func (*Event_ClientOnline) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Event_ClientOnline) GetInfo() *OnlineUserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type Event_ClientOffline struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The client's username.
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_ClientOffline) Reset() {
	*x = Event_ClientOffline{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_ClientOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_ClientOffline) ProtoMessage() {}

func (x *Event_ClientOffline) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_ClientOffline.ProtoReflect.Descriptor instead.
func (*Event_ClientOffline) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Event_ClientOffline) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ServerInfo_State struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current connection state.
	ConnState     ServerConnState `protobuf:"varint,1,opt,name=conn_state,json=connState,proto3,enum=pb.clientrpc.v1.ServerConnState" json:"conn_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo_State) Reset() {
	*x = ServerInfo_State{}
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo_State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo_State) ProtoMessage() {}

func (x *ServerInfo_State) ProtoReflect() protoreflect.Message {
	mi := &file_pb_clientrpc_v1_rpc_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo_State.ProtoReflect.Descriptor instead.
func (*ServerInfo_State) Descriptor() ([]byte, []int) {
	return file_pb_clientrpc_v1_rpc_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ServerInfo_State) GetConnState() ServerConnState {
	if x != nil {
		return x.ConnState
	}
	return ServerConnState_SERVER_CONN_STATE_UNSPECIFIED
}

var File_pb_clientrpc_v1_rpc_proto protoreflect.FileDescriptor

const file_pb_clientrpc_v1_rpc_proto_rawDesc = "" +
	"\n" +
	"\x19pb/clientrpc/v1/rpc.proto\x12\x0fpb.clientrpc.v1\"\x97\x05\n" +
	"\x05Event\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.pb.clientrpc.v1.Event.TypeR\x04type\x12R\n" +
	"\vserver_conn\x18\x02 \x01(\v2,.pb.clientrpc.v1.Event.ServerConnStateChangeH\x00R\n" +
	"serverConn\x88\x01\x01\x12M\n" +
	"\rclient_online\x18\x03 \x01(\v2#.pb.clientrpc.v1.Event.ClientOnlineH\x01R\fclientOnline\x88\x01\x01\x12P\n" +
	"\x0eclient_offline\x18\x04 \x01(\v2$.pb.clientrpc.v1.Event.ClientOfflineH\x02R\rclientOffline\x88\x01\x01\x1aO\n" +
	"\x15ServerConnStateChange\x126\n" +
	"\x05state\x18\x02 \x01(\x0e2 .pb.clientrpc.v1.ServerConnStateR\x05state\x1aC\n" +
	"\fClientOnline\x123\n" +
	"\x04info\x18\x01 \x01(\v2\x1f.pb.clientrpc.v1.OnlineUserInfoR\x04info\x1a+\n" +
	"\rClientOffline\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"p\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dTYPE_SERVER_CONN_STATE_CHANGE\x10\x01\x12\x16\n" +
	"\x12TYPE_CLIENT_ONLINE\x10\x02\x12\x17\n" +
	"\x13TYPE_CLIENT_OFFLINE\x10\x03B\x0e\n" +
	"\f_server_connB\x10\n" +
	"\x0e_client_onlineB\x11\n" +
	"\x0f_client_offline\"/\n" +
	"\fEventContext\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\"L\n" +
	"\x0eLogMessageAttr\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x8e\x01\n" +
	"\n" +
	"LogMessage\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1d\n" +
	"\n" +
	"created_ts\x18\x02 \x01(\x03R\tcreatedTs\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x125\n" +
	"\x05attrs\x18\x04 \x03(\v2\x1f.pb.clientrpc.v1.LogMessageAttrR\x05attrs\"\xa0\x02\n" +
	"\n" +
	"ServerInfo\x127\n" +
	"\x05state\x18\x01 \x01(\v2!.pb.clientrpc.v1.ServerInfo.StateR\x05state\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04room\x18\x05 \x01(\tR\x04room\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"created_ts\x18\a \x01(\x03R\tcreatedTs\x1aH\n" +
	"\x05State\x12?\n" +
	"\n" +
	"conn_state\x18\x01 \x01(\x0e2 .pb.clientrpc.v1.ServerConnStateR\tconnState\"s\n" +
	"\tShareInfo\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"created_ts\x18\x04 \x01(\x03R\tcreatedTs\",\n" +
	"\x0eOnlineUserInfo\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"I\n" +
	"\bFileMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"\x15\n" +
	"\x13StreamEventsRequest\"}\n" +
	"\x14StreamEventsResponse\x12,\n" +
	"\x05event\x18\x01 \x01(\v2\x16.pb.clientrpc.v1.EventR\x05event\x127\n" +
	"\acontext\x18\x02 \x01(\v2\x1d.pb.clientrpc.v1.EventContextR\acontext\"\\\n" +
	"\x11StreamLogsRequest\x120\n" +
	"\x12send_logs_after_ts\x18\x01 \x01(\x03H\x00R\x0fsendLogsAfterTs\x88\x01\x01B\x15\n" +
	"\x13_send_logs_after_ts\"E\n" +
	"\x12StreamLogsResponse\x12/\n" +
	"\x04logs\x18\x01 \x03(\v2\x1b.pb.clientrpc.v1.LogMessageR\x04logs\"\r\n" +
	"\vStopRequest\"\x0e\n" +
	"\fStopResponse\"\x16\n" +
	"\x14GetClientInfoRequest\"?\n" +
	"\x15GetClientInfoResponse\x12&\n" +
	"\x0ffile_server_url\x18\x01 \x01(\tR\rfileServerUrl\"\x13\n" +
	"\x11GetServersRequest\"K\n" +
	"\x12GetServersResponse\x125\n" +
	"\aservers\x18\x01 \x03(\v2\x1b.pb.clientrpc.v1.ServerInfoR\aservers\"\x8f\x01\n" +
	"\x13CreateServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04room\x18\x03 \x01(\tR\x04room\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"K\n" +
	"\x14CreateServerResponse\x123\n" +
	"\x06server\x18\x01 \x01(\v2\x1b.pb.clientrpc.v1.ServerInfoR\x06server\")\n" +
	"\x13DeleteServerRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x16\n" +
	"\x14DeleteServerResponse\"*\n" +
	"\x14ConnectServerRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x17\n" +
	"\x15ConnectServerResponse\"-\n" +
	"\x17DisconnectServerRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x1a\n" +
	"\x18DisconnectServerResponse\"\xf4\x01\n" +
	"\x13UpdateServerRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x03 \x01(\tH\x01R\aaddress\x88\x01\x01\x12\x17\n" +
	"\x04room\x18\x04 \x01(\tH\x02R\x04room\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x05 \x01(\tH\x03R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x06 \x01(\tH\x04R\bpassword\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_addressB\a\n" +
	"\x05_roomB\v\n" +
	"\t_usernameB\v\n" +
	"\t_password\"K\n" +
	"\x14UpdateServerResponse\x123\n" +
	"\x06server\x18\x01 \x01(\v2\x1b.pb.clientrpc.v1.ServerInfoR\x06server\"3\n" +
	"\x10GetSharesRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\"G\n" +
	"\x11GetSharesResponse\x122\n" +
	"\x06shares\x18\x01 \x03(\v2\x1a.pb.clientrpc.v1.ShareInfoR\x06shares\"]\n" +
	"\x12CreateShareRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"G\n" +
	"\x13CreateShareResponse\x120\n" +
	"\x05share\x18\x01 \x01(\v2\x1a.pb.clientrpc.v1.ShareInfoR\x05share\"I\n" +
	"\x12DeleteShareRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x15\n" +
	"\x13DeleteShareResponse\"e\n" +
	"\x12GetDirFilesRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"J\n" +
	"\x13GetDirFilesResponse\x123\n" +
	"\acontent\x18\x02 \x03(\v2\x19.pb.clientrpc.v1.FileMetaR\acontent\"e\n" +
	"\x12GetFileMetaRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"D\n" +
	"\x13GetFileMetaResponse\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.pb.clientrpc.v1.FileMetaR\x04meta\"8\n" +
	"\x15GetOnlineUsersRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\"O\n" +
	"\x16GetOnlineUsersResponse\x125\n" +
	"\x05users\x18\x01 \x03(\v2\x1f.pb.clientrpc.v1.OnlineUserInfoR\x05users\"\x8d\x01\n" +
	"\x1cChangeAccountPasswordRequest\x12\x1f\n" +
	"\vserver_uuid\x18\x01 \x01(\tR\n" +
	"serverUuid\x12)\n" +
	"\x10current_password\x18\x02 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"\x1f\n" +
	"\x1dChangeAccountPasswordResponse*\x8d\x01\n" +
	"\x0fServerConnState\x12!\n" +
	"\x1dSERVER_CONN_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SERVER_CONN_STATE_CLOSED\x10\x01\x12\x1d\n" +
	"\x19SERVER_CONN_STATE_OPENING\x10\x02\x12\x1a\n" +
	"\x16SERVER_CONN_STATE_OPEN\x10\x032\xe3\f\n" +
	"\x10ClientRpcService\x12Y\n" +
	"\n" +
	"StreamLogs\x12\".pb.clientrpc.v1.StreamLogsRequest\x1a#.pb.clientrpc.v1.StreamLogsResponse\"\x000\x01\x12_\n" +
	"\fStreamEvents\x12$.pb.clientrpc.v1.StreamEventsRequest\x1a%.pb.clientrpc.v1.StreamEventsResponse\"\x000\x01\x12E\n" +
	"\x04Stop\x12\x1c.pb.clientrpc.v1.StopRequest\x1a\x1d.pb.clientrpc.v1.StopResponse\"\x00\x12`\n" +
	"\rGetClientInfo\x12%.pb.clientrpc.v1.GetClientInfoRequest\x1a&.pb.clientrpc.v1.GetClientInfoResponse\"\x00\x12W\n" +
	"\n" +
	"GetServers\x12\".pb.clientrpc.v1.GetServersRequest\x1a#.pb.clientrpc.v1.GetServersResponse\"\x00\x12]\n" +
	"\fCreateServer\x12$.pb.clientrpc.v1.CreateServerRequest\x1a%.pb.clientrpc.v1.CreateServerResponse\"\x00\x12]\n" +
	"\fDeleteServer\x12$.pb.clientrpc.v1.DeleteServerRequest\x1a%.pb.clientrpc.v1.DeleteServerResponse\"\x00\x12`\n" +
	"\rConnectServer\x12%.pb.clientrpc.v1.ConnectServerRequest\x1a&.pb.clientrpc.v1.ConnectServerResponse\"\x00\x12i\n" +
	"\x10DisconnectServer\x12(.pb.clientrpc.v1.DisconnectServerRequest\x1a).pb.clientrpc.v1.DisconnectServerResponse\"\x00\x12]\n" +
	"\fUpdateServer\x12$.pb.clientrpc.v1.UpdateServerRequest\x1a%.pb.clientrpc.v1.UpdateServerResponse\"\x00\x12T\n" +
	"\tGetShares\x12!.pb.clientrpc.v1.GetSharesRequest\x1a\".pb.clientrpc.v1.GetSharesResponse\"\x00\x12Z\n" +
	"\vCreateShare\x12#.pb.clientrpc.v1.CreateShareRequest\x1a$.pb.clientrpc.v1.CreateShareResponse\"\x00\x12Z\n" +
	"\vDeleteShare\x12#.pb.clientrpc.v1.DeleteShareRequest\x1a$.pb.clientrpc.v1.DeleteShareResponse\"\x00\x12\\\n" +
	"\vGetDirFiles\x12#.pb.clientrpc.v1.GetDirFilesRequest\x1a$.pb.clientrpc.v1.GetDirFilesResponse\"\x000\x01\x12Z\n" +
	"\vGetFileMeta\x12#.pb.clientrpc.v1.GetFileMetaRequest\x1a$.pb.clientrpc.v1.GetFileMetaResponse\"\x00\x12e\n" +
	"\x0eGetOnlineUsers\x12&.pb.clientrpc.v1.GetOnlineUsersRequest\x1a'.pb.clientrpc.v1.GetOnlineUsersResponse\"\x000\x01\x12x\n" +
	"\x15ChangeAccountPassword\x12-.pb.clientrpc.v1.ChangeAccountPasswordRequest\x1a..pb.clientrpc.v1.ChangeAccountPasswordResponse\"\x00B\xb1\x01\n" +
	"\x13com.pb.clientrpc.v1B\bRpcProtoP\x01Z2friendnet.org/protocol/pb/clientrpc/v1;clientrpcv1\xa2\x02\x03PCX\xaa\x02\x0fPb.Clientrpc.V1\xca\x02\x0fPb\\Clientrpc\\V1\xe2\x02\x1bPb\\Clientrpc\\V1\\GPBMetadata\xea\x02\x11Pb::Clientrpc::V1b\x06proto3"

var (
	file_pb_clientrpc_v1_rpc_proto_rawDescOnce sync.Once
	file_pb_clientrpc_v1_rpc_proto_rawDescData []byte
)

func file_pb_clientrpc_v1_rpc_proto_rawDescGZIP() []byte {
	file_pb_clientrpc_v1_rpc_proto_rawDescOnce.Do(func() {
		file_pb_clientrpc_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_clientrpc_v1_rpc_proto_rawDesc), len(file_pb_clientrpc_v1_rpc_proto_rawDesc)))
	})
	return file_pb_clientrpc_v1_rpc_proto_rawDescData
}

var file_pb_clientrpc_v1_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_clientrpc_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_pb_clientrpc_v1_rpc_proto_goTypes = []any{
	(ServerConnState)(0),                  // 0: pb.clientrpc.v1.ServerConnState
	(Event_Type)(0),                       // 1: pb.clientrpc.v1.Event.Type
	(*Event)(nil),                         // 2: pb.clientrpc.v1.Event
	(*EventContext)(nil),                  // 3: pb.clientrpc.v1.EventContext
	(*LogMessageAttr)(nil),                // 4: pb.clientrpc.v1.LogMessageAttr
	(*LogMessage)(nil),                    // 5: pb.clientrpc.v1.LogMessage
	(*ServerInfo)(nil),                    // 6: pb.clientrpc.v1.ServerInfo
	(*ShareInfo)(nil),                     // 7: pb.clientrpc.v1.ShareInfo
	(*OnlineUserInfo)(nil),                // 8: pb.clientrpc.v1.OnlineUserInfo
	(*FileMeta)(nil),                      // 9: pb.clientrpc.v1.FileMeta
	(*StreamEventsRequest)(nil),           // 10: pb.clientrpc.v1.StreamEventsRequest
	(*StreamEventsResponse)(nil),          // 11: pb.clientrpc.v1.StreamEventsResponse
	(*StreamLogsRequest)(nil),             // 12: pb.clientrpc.v1.StreamLogsRequest
	(*StreamLogsResponse)(nil),            // 13: pb.clientrpc.v1.StreamLogsResponse
	(*StopRequest)(nil),                   // 14: pb.clientrpc.v1.StopRequest
	(*StopResponse)(nil),                  // 15: pb.clientrpc.v1.StopResponse
	(*GetClientInfoRequest)(nil),          // 16: pb.clientrpc.v1.GetClientInfoRequest
	(*GetClientInfoResponse)(nil),         // 17: pb.clientrpc.v1.GetClientInfoResponse
	(*GetServersRequest)(nil),             // 18: pb.clientrpc.v1.GetServersRequest
	(*GetServersResponse)(nil),            // 19: pb.clientrpc.v1.GetServersResponse
	(*CreateServerRequest)(nil),           // 20: pb.clientrpc.v1.CreateServerRequest
	(*CreateServerResponse)(nil),          // 21: pb.clientrpc.v1.CreateServerResponse
	(*DeleteServerRequest)(nil),           // 22: pb.clientrpc.v1.DeleteServerRequest
	(*DeleteServerResponse)(nil),          // 23: pb.clientrpc.v1.DeleteServerResponse
	(*ConnectServerRequest)(nil),          // 24: pb.clientrpc.v1.ConnectServerRequest
	(*ConnectServerResponse)(nil),         // 25: pb.clientrpc.v1.ConnectServerResponse
	(*DisconnectServerRequest)(nil),       // 26: pb.clientrpc.v1.DisconnectServerRequest
	(*DisconnectServerResponse)(nil),      // 27: pb.clientrpc.v1.DisconnectServerResponse
	(*UpdateServerRequest)(nil),           // 28: pb.clientrpc.v1.UpdateServerRequest
	(*UpdateServerResponse)(nil),          // 29: pb.clientrpc.v1.UpdateServerResponse
	(*GetSharesRequest)(nil),              // 30: pb.clientrpc.v1.GetSharesRequest
	(*GetSharesResponse)(nil),             // 31: pb.clientrpc.v1.GetSharesResponse
	(*CreateShareRequest)(nil),            // 32: pb.clientrpc.v1.CreateShareRequest
	(*CreateShareResponse)(nil),           // 33: pb.clientrpc.v1.CreateShareResponse
	(*DeleteShareRequest)(nil),            // 34: pb.clientrpc.v1.DeleteShareRequest
	(*DeleteShareResponse)(nil),           // 35: pb.clientrpc.v1.DeleteShareResponse
	(*GetDirFilesRequest)(nil),            // 36: pb.clientrpc.v1.GetDirFilesRequest
	(*GetDirFilesResponse)(nil),           // 37: pb.clientrpc.v1.GetDirFilesResponse
	(*GetFileMetaRequest)(nil),            // 38: pb.clientrpc.v1.GetFileMetaRequest
	(*GetFileMetaResponse)(nil),           // 39: pb.clientrpc.v1.GetFileMetaResponse
	(*GetOnlineUsersRequest)(nil),         // 40: pb.clientrpc.v1.GetOnlineUsersRequest
	(*GetOnlineUsersResponse)(nil),        // 41: pb.clientrpc.v1.GetOnlineUsersResponse
	(*ChangeAccountPasswordRequest)(nil),  // 42: pb.clientrpc.v1.ChangeAccountPasswordRequest
	(*ChangeAccountPasswordResponse)(nil), // 43: pb.clientrpc.v1.ChangeAccountPasswordResponse
	(*Event_ServerConnStateChange)(nil),   // 44: pb.clientrpc.v1.Event.ServerConnStateChange
	(*Event_ClientOnline)(nil),            // 45: pb.clientrpc.v1.Event.ClientOnline
	(*Event_ClientOffline)(nil),           // 46: pb.clientrpc.v1.Event.ClientOffline
	(*ServerInfo_State)(nil),              // 47: pb.clientrpc.v1.ServerInfo.State
}
var file_pb_clientrpc_v1_rpc_proto_depIdxs = []int32{
	1,  // 0: pb.clientrpc.v1.Event.type:type_name -> pb.clientrpc.v1.Event.Type
	44, // 1: pb.clientrpc.v1.Event.server_conn:type_name -> pb.clientrpc.v1.Event.ServerConnStateChange
	45, // 2: pb.clientrpc.v1.Event.client_online:type_name -> pb.clientrpc.v1.Event.ClientOnline
	46, // 3: pb.clientrpc.v1.Event.client_offline:type_name -> pb.clientrpc.v1.Event.ClientOffline
	4,  // 4: pb.clientrpc.v1.LogMessage.attrs:type_name -> pb.clientrpc.v1.LogMessageAttr
	47, // 5: pb.clientrpc.v1.ServerInfo.state:type_name -> pb.clientrpc.v1.ServerInfo.State
	2,  // 6: pb.clientrpc.v1.StreamEventsResponse.event:type_name -> pb.clientrpc.v1.Event
	3,  // 7: pb.clientrpc.v1.StreamEventsResponse.context:type_name -> pb.clientrpc.v1.EventContext
	5,  // 8: pb.clientrpc.v1.StreamLogsResponse.logs:type_name -> pb.clientrpc.v1.LogMessage
	6,  // 9: pb.clientrpc.v1.GetServersResponse.servers:type_name -> pb.clientrpc.v1.ServerInfo
	6,  // 10: pb.clientrpc.v1.CreateServerResponse.server:type_name -> pb.clientrpc.v1.ServerInfo
	6,  // 11: pb.clientrpc.v1.UpdateServerResponse.server:type_name -> pb.clientrpc.v1.ServerInfo
	7,  // 12: pb.clientrpc.v1.GetSharesResponse.shares:type_name -> pb.clientrpc.v1.ShareInfo
	7,  // 13: pb.clientrpc.v1.CreateShareResponse.share:type_name -> pb.clientrpc.v1.ShareInfo
	9,  // 14: pb.clientrpc.v1.GetDirFilesResponse.content:type_name -> pb.clientrpc.v1.FileMeta
	9,  // 15: pb.clientrpc.v1.GetFileMetaResponse.meta:type_name -> pb.clientrpc.v1.FileMeta
	8,  // 16: pb.clientrpc.v1.GetOnlineUsersResponse.users:type_name -> pb.clientrpc.v1.OnlineUserInfo
	0,  // 17: pb.clientrpc.v1.Event.ServerConnStateChange.state:type_name -> pb.clientrpc.v1.ServerConnState
	8,  // 18: pb.clientrpc.v1.Event.ClientOnline.info:type_name -> pb.clientrpc.v1.OnlineUserInfo
	0,  // 19: pb.clientrpc.v1.ServerInfo.State.conn_state:type_name -> pb.clientrpc.v1.ServerConnState
	12, // 20: pb.clientrpc.v1.ClientRpcService.StreamLogs:input_type -> pb.clientrpc.v1.StreamLogsRequest
	10, // 21: pb.clientrpc.v1.ClientRpcService.StreamEvents:input_type -> pb.clientrpc.v1.StreamEventsRequest
	14, // 22: pb.clientrpc.v1.ClientRpcService.Stop:input_type -> pb.clientrpc.v1.StopRequest
	16, // 23: pb.clientrpc.v1.ClientRpcService.GetClientInfo:input_type -> pb.clientrpc.v1.GetClientInfoRequest
	18, // 24: pb.clientrpc.v1.ClientRpcService.GetServers:input_type -> pb.clientrpc.v1.GetServersRequest
	20, // 25: pb.clientrpc.v1.ClientRpcService.CreateServer:input_type -> pb.clientrpc.v1.CreateServerRequest
	22, // 26: pb.clientrpc.v1.ClientRpcService.DeleteServer:input_type -> pb.clientrpc.v1.DeleteServerRequest
	24, // 27: pb.clientrpc.v1.ClientRpcService.ConnectServer:input_type -> pb.clientrpc.v1.ConnectServerRequest
	26, // 28: pb.clientrpc.v1.ClientRpcService.DisconnectServer:input_type -> pb.clientrpc.v1.DisconnectServerRequest
	28, // 29: pb.clientrpc.v1.ClientRpcService.UpdateServer:input_type -> pb.clientrpc.v1.UpdateServerRequest
	30, // 30: pb.clientrpc.v1.ClientRpcService.GetShares:input_type -> pb.clientrpc.v1.GetSharesRequest
	32, // 31: pb.clientrpc.v1.ClientRpcService.CreateShare:input_type -> pb.clientrpc.v1.CreateShareRequest
	34, // 32: pb.clientrpc.v1.ClientRpcService.DeleteShare:input_type -> pb.clientrpc.v1.DeleteShareRequest
	36, // 33: pb.clientrpc.v1.ClientRpcService.GetDirFiles:input_type -> pb.clientrpc.v1.GetDirFilesRequest
	38, // 34: pb.clientrpc.v1.ClientRpcService.GetFileMeta:input_type -> pb.clientrpc.v1.GetFileMetaRequest
	40, // 35: pb.clientrpc.v1.ClientRpcService.GetOnlineUsers:input_type -> pb.clientrpc.v1.GetOnlineUsersRequest
	42, // 36: pb.clientrpc.v1.ClientRpcService.ChangeAccountPassword:input_type -> pb.clientrpc.v1.ChangeAccountPasswordRequest
	13, // 37: pb.clientrpc.v1.ClientRpcService.StreamLogs:output_type -> pb.clientrpc.v1.StreamLogsResponse
	11, // 38: pb.clientrpc.v1.ClientRpcService.StreamEvents:output_type -> pb.clientrpc.v1.StreamEventsResponse
	15, // 39: pb.clientrpc.v1.ClientRpcService.Stop:output_type -> pb.clientrpc.v1.StopResponse
	17, // 40: pb.clientrpc.v1.ClientRpcService.GetClientInfo:output_type -> pb.clientrpc.v1.GetClientInfoResponse
	19, // 41: pb.clientrpc.v1.ClientRpcService.GetServers:output_type -> pb.clientrpc.v1.GetServersResponse
	21, // 42: pb.clientrpc.v1.ClientRpcService.CreateServer:output_type -> pb.clientrpc.v1.CreateServerResponse
	23, // 43: pb.clientrpc.v1.ClientRpcService.DeleteServer:output_type -> pb.clientrpc.v1.DeleteServerResponse
	25, // 44: pb.clientrpc.v1.ClientRpcService.ConnectServer:output_type -> pb.clientrpc.v1.ConnectServerResponse
	27, // 45: pb.clientrpc.v1.ClientRpcService.DisconnectServer:output_type -> pb.clientrpc.v1.DisconnectServerResponse
	29, // 46: pb.clientrpc.v1.ClientRpcService.UpdateServer:output_type -> pb.clientrpc.v1.UpdateServerResponse
	31, // 47: pb.clientrpc.v1.ClientRpcService.GetShares:output_type -> pb.clientrpc.v1.GetSharesResponse
	33, // 48: pb.clientrpc.v1.ClientRpcService.CreateShare:output_type -> pb.clientrpc.v1.CreateShareResponse
	35, // 49: pb.clientrpc.v1.ClientRpcService.DeleteShare:output_type -> pb.clientrpc.v1.DeleteShareResponse
	37, // 50: pb.clientrpc.v1.ClientRpcService.GetDirFiles:output_type -> pb.clientrpc.v1.GetDirFilesResponse
	39, // 51: pb.clientrpc.v1.ClientRpcService.GetFileMeta:output_type -> pb.clientrpc.v1.GetFileMetaResponse
	41, // 52: pb.clientrpc.v1.ClientRpcService.GetOnlineUsers:output_type -> pb.clientrpc.v1.GetOnlineUsersResponse
	43, // 53: pb.clientrpc.v1.ClientRpcService.ChangeAccountPassword:output_type -> pb.clientrpc.v1.ChangeAccountPasswordResponse
	37, // [37:54] is the sub-list for method output_type
	20, // [20:37] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_pb_clientrpc_v1_rpc_proto_init() }
func file_pb_clientrpc_v1_rpc_proto_init() {
	if File_pb_clientrpc_v1_rpc_proto != nil {
		return
	}
	file_pb_clientrpc_v1_rpc_proto_msgTypes[0].OneofWrappers = []any{}
	file_pb_clientrpc_v1_rpc_proto_msgTypes[10].OneofWrappers = []any{}
	file_pb_clientrpc_v1_rpc_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_clientrpc_v1_rpc_proto_rawDesc), len(file_pb_clientrpc_v1_rpc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_clientrpc_v1_rpc_proto_goTypes,
		DependencyIndexes: file_pb_clientrpc_v1_rpc_proto_depIdxs,
		EnumInfos:         file_pb_clientrpc_v1_rpc_proto_enumTypes,
		MessageInfos:      file_pb_clientrpc_v1_rpc_proto_msgTypes,
	}.Build()
	File_pb_clientrpc_v1_rpc_proto = out.File
	file_pb_clientrpc_v1_rpc_proto_goTypes = nil
	file_pb_clientrpc_v1_rpc_proto_depIdxs = nil
}
