services:
    friendnet-server:
        image: git.termer.net/termer/friendnet-server:latest
        restart: unless-stopped

        network_mode: host

        volumes:
            - ./config:/etc/friendnet/
            - ./data:/var/lib/friendnet/
