# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
    SERVER_BUILD: |
        mkdir -p adminui/dist && \
        cd server && \
        CGO_ENABLED=0 go build \
            -trimpath -ldflags="-s -w" \
            -o friendnet-server \
            friendnet.org/server/cmd/server

    CLIENT_BUILD: |
        mkdir -p webui/dist && \
        CGO_ENABLED=0 go build \
            -trimpath \
            -ldflags="$LD_FLAGS" \
            -o client/friendnet-client"$O_SUFFIX" \
            friendnet.org/client/cmd/client

    RPCCLIENT_BUILD: |
        cd rpcclient && \
        CGO_ENABLED=0 go build \
            -trimpath -ldflags="-s -w" \
            -o friendnet-rpcclient \
            friendnet.org/rpcclient/cmd/cli

    SERVER_DOCKER_BUILD: |
        docker build -t git.termer.net/termer/friendnet-server:"$TAG" -f server.Dockerfile .

    SERVER_DOCKER_PUBLISH: |
        docker push git.termer.net/termer/friendnet-server:"$TAG"

tasks:
    pb:
        desc: Generates source files from protobuf schemas
        cmds:
            - cd protocol && ../tool/bin/buf lint && ../tool/bin/buf generate
            - cd webui && npx buf lint && npx buf generate
            - cd server-widget && npx buf lint && npx buf generate
            - cd adminui && npx buf lint && npx buf generate

    adminui:
        desc: Builds the server admin UI
        cmd:
            cd adminui && go generate

    server:
        desc: Builds the server
        deps:
            - adminui
            - server-noui

    server-noui:
        desc: Builds the server (skips building the admin UI)
        cmd:
            \{{.SERVER_BUILD}}

    server-linux-amd64-noui:
        env:
            GOOS: linux
            GOARCH: amd64
        cmd:
            \{{.SERVER_BUILD}}

    server-linux-arm64-noui:
        env:
            GOOS: linux
            GOARCH: arm64
        cmd: \{{.SERVER_BUILD}}

    webui:
        desc:
            Builds the client web UI
        cmd:
            cd webui && go generate

    client:
        desc:
            Builds the client
        deps:
            - webui
            - client-noui

    client-noui:
        desc:
            Builds teh client (skips build the web UI)
        cmd:
            \{{.CLIENT_BUILD}}

    client-windows-amd64-noui:
        env:
            GOOS: windows
            GOARCH: amd64
            LD_FLAGS: -H windowsgui
            O_SUFFIX: .exe
        cmd:
            \{{.CLIENT_BUILD}}

    client-linux-amd64-noui:
        env:
            GOOS: linux
            GOARCH: amd64
        cmd:
            \{{.CLIENT_BUILD}}

    client-linux-arm64-noui:
        env:
            GOOS: linux
            GOARCH: arm64
        cmd:
            \{{.CLIENT_BUILD}}

    client-darwin-arm64-noui:
        env:
            GOOS: darwin
            GOARCH: arm64
        cmd:
            \{{.CLIENT_BUILD}}

    client-freebsd-amd64-noui:
        env:
            GOOS: freebsd
            GOARCH: amd64
        cmd:
            \{{.CLIENT_BUILD}}

    client-debs:
        desc:
            Builds Debian packages for the client
        cmd:
            cd packaging && node index.ts deb

    client-debs-noui:
        desc:
            Builds Debian packages for the client (skips building the web UI)
        cmd:
            cd packaging && node index.ts deb --no-ui

    client-appimages:
        desc:
            Builds AppImage packages for the client
        cmd:
            cd packaging && node index.ts appimage

    client-appimages-noui:
        desc:
            Builds AppImage packages for the client (skips building the web UI)
        cmd:
            cd packaging && node index.ts appimage --no-ui

    rpcclient:
        desc:
            Builds the server RPC client
        cmd:
            \{{.RPCCLIENT_BUILD}}

    rpcclient-linux-amd64:
        env:
            GOOS: linux
            GOARCH: amd64
        cmd:
            \{{.RPCCLIENT_BUILD}}

    rpcclient-linux-arm64:
        env:
            GOOS: linux
            GOARCH: arm64
        cmd:
            \{{.RPCCLIENT_BUILD}}

    run-rpcclient:
        desc:
            Runs the RPC client for development.
            Assumes that the server RPC socket is in the "server" directory.
        interactive: true
        deps:
            - rpcclient
        cmd:
            cd server && ../rpcclient/friendnet-rpcclient

    server-docker:
        desc:
            Builds the server Docker image
        env:
            TAG: latest
        cmd:
            \{{.SERVER_DOCKER_BUILD}}

    server-docker-publish:
        desc:
            Builds and publishes the server Docker image
        deps:
            - server-docker
        env:
            TAG: latest
        cmd:
            \{{.SERVER_DOCKER_PUBLISH}}

    server-docker-dev:
        desc:
            Builds the server Docker image (dev tag)
        env:
            TAG: dev
        cmd:
            \{{.SERVER_DOCKER_BUILD}}

    server-docker-dev-publish:
        desc:
            Builds and publishes the server Docker image (dev tag)
        deps:
            - server-docker
        env:
            TAG: dev
        cmd:
            \{{.SERVER_DOCKER_BUILD}}

    website:
        desc:
            Builds the website
        cmd:
            cd website && npm ci && npm run build

    release-artifacts:
        desc:
            Builds all release artifacts
        cmds:
            - rm -rf /tmp/fn-release
            - mkdir /tmp/fn-release

            - task: webui

            - task: client-windows-amd64-noui
            - mv client/friendnet-client.exe /tmp/fn-release/friendnet-client-windows_amd64.exe

            - task: client-debs-noui
            - mv client/*.deb /tmp/fn-release/
            - task: client-appimages-noui
            - mv client/*.AppImage /tmp/fn-release/

            - task: adminui

            - task: server-linux-amd64-noui
            - mv server/friendnet-server /tmp/fn-release/server
            - task: rpcclient-linux-amd64
            - mv rpcclient/friendnet-rpcclient /tmp/fn-release/rpcclient
            - chmod +x /tmp/fn-release/*
            - cd /tmp/fn-release && tar -czf friendnet-server-linux_amd64.tar.gz server rpcclient
            - rm /tmp/fn-release/server && rm /tmp/fn-release/rpcclient

            - task: server-linux-arm64-noui
            - mv server/friendnet-server /tmp/fn-release/server
            - task: rpcclient-linux-arm64
            - mv rpcclient/friendnet-rpcclient /tmp/fn-release/rpcclient
            - chmod +x /tmp/fn-release/*
            - cd /tmp/fn-release && tar -czf friendnet-server-linux_arm64.tar.gz server rpcclient
            - rm /tmp/fn-release/server && rm /tmp/fn-release/rpcclient

            - task: server-docker-publish
            - task: server-docker-dev-publish

            - echo "Artifacts in /tmp/fn-release, and new server Docker image pushed"
