// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pb/v1/protocol.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Types of protocol messages
type MsgType int32

const (
	// Do not use.
	MsgType_MSG_TYPE_UNSPECIFIED MsgType = 0
	// [C2S, S2C, C2C] A ping message.
	// May be sent by either the client or server, but the other must respond with MSG_TYPE_PONG.
	// Must be responded to with MSG_TYPE_PONG, or the connection will be terminated.
	// Either side may have its own arbitrary timeout which may cause disconnection if not met.
	// Expected: Message MSG_TYPE_PONG.
	MsgType_MSG_TYPE_PING MsgType = 1
	// [C2S, S2C, C2C] Response to MSG_TYPE_PING.
	MsgType_MSG_TYPE_PONG MsgType = 2
	// [C2S, S2C, C2C] Acknowledgement of success.
	// Sent as a reply to other messages.
	MsgType_MSG_TYPE_ACKNOWLEDGED MsgType = 3
	// [C2S, S2C, C2C] An error message.
	// Sent as a reply to other messages.
	MsgType_MSG_TYPE_ERROR MsgType = 4
	// [C2S] Initial client version negotiation.
	MsgType_MSG_TYPE_VERSION MsgType = 5
	// [S2C] Indicates that the server accepted the client's protocol version.
	MsgType_MSG_TYPE_VERSION_ACCEPTED MsgType = 6
	// [S2C] Indicates that the server rejected the client's protocol version.
	MsgType_MSG_TYPE_VERSION_REJECTED MsgType = 7
	// [C2S] Initial client authentication with the server.
	MsgType_MSG_TYPE_AUTHENTICATE MsgType = 8
	// [S2C] Indicates that client authentication was accepted.
	MsgType_MSG_TYPE_AUTH_ACCEPTED MsgType = 9
	// [S2C] Indicates that client authentication was denied.
	MsgType_MSG_TYPE_AUTH_REJECTED MsgType = 10
	// [C2S] Request to open an outbound proxy to a connected peer.
	// The server will cancel the stream with an error if the target peer could not be contacted.
	// If successful, the stream will be converted to a proxied stream to the target peer.
	MsgType_MSG_TYPE_OPEN_OUTBOUND_PROXY MsgType = 11
	// [S2C] Notification of a new inbound proxy stream from another peer.
	// The client can choose to cancel the stream or send data on it.
	// All data after the notification message comes from the origin peer.
	MsgType_MSG_TYPE_INBOUND_PROXY MsgType = 12
	// [C2C] Request to get files inside a user's directory.
	// Expected: Either:
	//   - Repeated message MSG_TYPE_DIR_FILES until stream is closed by receiver.
	//   - Message MSG_TYPE_ERROR of ERR_TYPE_FILE_NOT_EXIST.
	MsgType_MSG_TYPE_GET_DIR_FILES MsgType = 13
	// [C2C] A possibly non-exhaustive list of files in a directory.
	MsgType_MSG_TYPE_DIR_FILES MsgType = 14
	// [C2C] Request to get metadata about a file without reading it.
	// Expected: Either:
	//   - Message MSG_TYPE_FILE_META.
	//   - Message MSG_TYPE_ERROR of ERR_TYPE_FILE_NOT_EXIST.
	MsgType_MSG_TYPE_GET_FILE_META MsgType = 15
	// [C2C] Metadata about a file, including its size.
	MsgType_MSG_TYPE_FILE_META MsgType = 16
	// [C2C] Request to get a file's metadata and contents.
	// Expected: Either:
	//   - Message MSG_TYPE_FILE_META then the file's requested binary content until the stream is closed by receiver.
	//     If the file is a directory, the size will be zero and no content will be sent.
	//   - Message MSG_TYPE_ERROR of ERR_TYPE_FILE_NOT_EXIST.
	MsgType_MSG_TYPE_GET_FILE MsgType = 17
	// [C2S] Request to get a list of online users in the room.
	// Expected: Repeated message MSG_TYPE_ONLINE_USERS until stream is closed by receiver.
	MsgType_MSG_TYPE_GET_ONLINE_USERS MsgType = 18
	// [S2C] List of online users in the room.
	MsgType_MSG_TYPE_ONLINE_USERS MsgType = 19
	// [C2S] Notification to let the server know the client is disconnecting.
	// The client must not communicate with the server after sending this message.
	// Expected: Message MSG_TYPE_ACKNOWLEDGED.
	MsgType_MSG_TYPE_BYE MsgType = 20
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:  "MSG_TYPE_UNSPECIFIED",
		1:  "MSG_TYPE_PING",
		2:  "MSG_TYPE_PONG",
		3:  "MSG_TYPE_ACKNOWLEDGED",
		4:  "MSG_TYPE_ERROR",
		5:  "MSG_TYPE_VERSION",
		6:  "MSG_TYPE_VERSION_ACCEPTED",
		7:  "MSG_TYPE_VERSION_REJECTED",
		8:  "MSG_TYPE_AUTHENTICATE",
		9:  "MSG_TYPE_AUTH_ACCEPTED",
		10: "MSG_TYPE_AUTH_REJECTED",
		11: "MSG_TYPE_OPEN_OUTBOUND_PROXY",
		12: "MSG_TYPE_INBOUND_PROXY",
		13: "MSG_TYPE_GET_DIR_FILES",
		14: "MSG_TYPE_DIR_FILES",
		15: "MSG_TYPE_GET_FILE_META",
		16: "MSG_TYPE_FILE_META",
		17: "MSG_TYPE_GET_FILE",
		18: "MSG_TYPE_GET_ONLINE_USERS",
		19: "MSG_TYPE_ONLINE_USERS",
		20: "MSG_TYPE_BYE",
	}
	MsgType_value = map[string]int32{
		"MSG_TYPE_UNSPECIFIED":         0,
		"MSG_TYPE_PING":                1,
		"MSG_TYPE_PONG":                2,
		"MSG_TYPE_ACKNOWLEDGED":        3,
		"MSG_TYPE_ERROR":               4,
		"MSG_TYPE_VERSION":             5,
		"MSG_TYPE_VERSION_ACCEPTED":    6,
		"MSG_TYPE_VERSION_REJECTED":    7,
		"MSG_TYPE_AUTHENTICATE":        8,
		"MSG_TYPE_AUTH_ACCEPTED":       9,
		"MSG_TYPE_AUTH_REJECTED":       10,
		"MSG_TYPE_OPEN_OUTBOUND_PROXY": 11,
		"MSG_TYPE_INBOUND_PROXY":       12,
		"MSG_TYPE_GET_DIR_FILES":       13,
		"MSG_TYPE_DIR_FILES":           14,
		"MSG_TYPE_GET_FILE_META":       15,
		"MSG_TYPE_FILE_META":           16,
		"MSG_TYPE_GET_FILE":            17,
		"MSG_TYPE_GET_ONLINE_USERS":    18,
		"MSG_TYPE_ONLINE_USERS":        19,
		"MSG_TYPE_BYE":                 20,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_v1_protocol_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_pb_v1_protocol_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{0}
}

// Types of errors that can be returned in protocol error messages.
type ErrType int32

const (
	// Do not use.
	ErrType_ERR_TYPE_UNSPECIFIED ErrType = 0
	// An internal error occurred.
	ErrType_ERR_TYPE_INTERNAL ErrType = 1
	// An invalid message was received.
	ErrType_ERR_TYPE_MALFORMED_MESSAGE ErrType = 2
	// The message's payload exceeded the size limit.
	ErrType_ERR_TYPE_PAYLOAD_TOO_LARGE ErrType = 3
	// A required field was missing.
	ErrType_ERR_TYPE_MISSING_FIELDS ErrType = 4
	// An invalid field was received.
	ErrType_ERR_TYPE_INVALID_FIELDS ErrType = 5
	// A message was received, but its type was unexpected.
	ErrType_ERR_TYPE_UNEXPECTED_MSG_TYPE ErrType = 6
	// Requests were sent too quickly and the request was rate limited.
	ErrType_ERR_TYPE_RATE_LIMITED ErrType = 7
	// The file did not exist.
	ErrType_ERR_TYPE_FILE_NOT_EXIST ErrType = 8
	// Unimplemented functionality.
	ErrType_ERR_TYPE_UNIMPLEMENTED ErrType = 9
	// Permission denied.
	ErrType_ERR_TYPE_PERMISSION_DENIED ErrType = 10
	// A path did not point to a directory.
	ErrType_ERR_TYPE_PATH_NOT_DIRECTORY ErrType = 11
)

// Enum value maps for ErrType.
var (
	ErrType_name = map[int32]string{
		0:  "ERR_TYPE_UNSPECIFIED",
		1:  "ERR_TYPE_INTERNAL",
		2:  "ERR_TYPE_MALFORMED_MESSAGE",
		3:  "ERR_TYPE_PAYLOAD_TOO_LARGE",
		4:  "ERR_TYPE_MISSING_FIELDS",
		5:  "ERR_TYPE_INVALID_FIELDS",
		6:  "ERR_TYPE_UNEXPECTED_MSG_TYPE",
		7:  "ERR_TYPE_RATE_LIMITED",
		8:  "ERR_TYPE_FILE_NOT_EXIST",
		9:  "ERR_TYPE_UNIMPLEMENTED",
		10: "ERR_TYPE_PERMISSION_DENIED",
		11: "ERR_TYPE_PATH_NOT_DIRECTORY",
	}
	ErrType_value = map[string]int32{
		"ERR_TYPE_UNSPECIFIED":         0,
		"ERR_TYPE_INTERNAL":            1,
		"ERR_TYPE_MALFORMED_MESSAGE":   2,
		"ERR_TYPE_PAYLOAD_TOO_LARGE":   3,
		"ERR_TYPE_MISSING_FIELDS":      4,
		"ERR_TYPE_INVALID_FIELDS":      5,
		"ERR_TYPE_UNEXPECTED_MSG_TYPE": 6,
		"ERR_TYPE_RATE_LIMITED":        7,
		"ERR_TYPE_FILE_NOT_EXIST":      8,
		"ERR_TYPE_UNIMPLEMENTED":       9,
		"ERR_TYPE_PERMISSION_DENIED":   10,
		"ERR_TYPE_PATH_NOT_DIRECTORY":  11,
	}
)

func (x ErrType) Enum() *ErrType {
	p := new(ErrType)
	*p = x
	return p
}

func (x ErrType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_v1_protocol_proto_enumTypes[1].Descriptor()
}

func (ErrType) Type() protoreflect.EnumType {
	return &file_pb_v1_protocol_proto_enumTypes[1]
}

func (x ErrType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrType.Descriptor instead.
func (ErrType) EnumDescriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{1}
}

// Reasons for a client's version being rejected
type VersionRejectionReason int32

const (
	// No reason specified.
	// More details may be in the rejection message.
	VersionRejectionReason_VERSION_REJECTION_REASON_UNSPECIFIED VersionRejectionReason = 0
	// The client's version is too old.
	VersionRejectionReason_VERSION_REJECTION_REASON_TOO_OLD VersionRejectionReason = 2
	// The client's version is too new.
	VersionRejectionReason_VERSION_REJECTION_REASON_TOO_NEW VersionRejectionReason = 3
)

// Enum value maps for VersionRejectionReason.
var (
	VersionRejectionReason_name = map[int32]string{
		0: "VERSION_REJECTION_REASON_UNSPECIFIED",
		2: "VERSION_REJECTION_REASON_TOO_OLD",
		3: "VERSION_REJECTION_REASON_TOO_NEW",
	}
	VersionRejectionReason_value = map[string]int32{
		"VERSION_REJECTION_REASON_UNSPECIFIED": 0,
		"VERSION_REJECTION_REASON_TOO_OLD":     2,
		"VERSION_REJECTION_REASON_TOO_NEW":     3,
	}
)

func (x VersionRejectionReason) Enum() *VersionRejectionReason {
	p := new(VersionRejectionReason)
	*p = x
	return p
}

func (x VersionRejectionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VersionRejectionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_v1_protocol_proto_enumTypes[2].Descriptor()
}

func (VersionRejectionReason) Type() protoreflect.EnumType {
	return &file_pb_v1_protocol_proto_enumTypes[2]
}

func (x VersionRejectionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VersionRejectionReason.Descriptor instead.
func (VersionRejectionReason) EnumDescriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{2}
}

// Reasons for a client's authentication request being rejected.
type AuthRejectionReason int32

const (
	// No reason specified.
	// More details may be in the rejection message.
	AuthRejectionReason_AUTH_REJECTION_REASON_UNSPECIFIED AuthRejectionReason = 0
	// The client provided invalid credentials (e.g. invalid token).
	AuthRejectionReason_AUTH_REJECTION_REASON_INVALID_CREDENTIALS AuthRejectionReason = 2
	// The user is banned and therefore not allowed to connect.
	AuthRejectionReason_AUTH_REJECTION_REASON_BANNED AuthRejectionReason = 3
)

// Enum value maps for AuthRejectionReason.
var (
	AuthRejectionReason_name = map[int32]string{
		0: "AUTH_REJECTION_REASON_UNSPECIFIED",
		2: "AUTH_REJECTION_REASON_INVALID_CREDENTIALS",
		3: "AUTH_REJECTION_REASON_BANNED",
	}
	AuthRejectionReason_value = map[string]int32{
		"AUTH_REJECTION_REASON_UNSPECIFIED":         0,
		"AUTH_REJECTION_REASON_INVALID_CREDENTIALS": 2,
		"AUTH_REJECTION_REASON_BANNED":              3,
	}
)

func (x AuthRejectionReason) Enum() *AuthRejectionReason {
	p := new(AuthRejectionReason)
	*p = x
	return p
}

func (x AuthRejectionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthRejectionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_v1_protocol_proto_enumTypes[3].Descriptor()
}

func (AuthRejectionReason) Type() protoreflect.EnumType {
	return &file_pb_v1_protocol_proto_enumTypes[3]
}

func (x AuthRejectionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthRejectionReason.Descriptor instead.
func (AuthRejectionReason) EnumDescriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{3}
}

// Ping message.
type MsgPing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The epoch millisecond timestamp when the message was sent.
	// Used to measure latency.
	SentTs        int64 `protobuf:"varint,1,opt,name=sent_ts,json=sentTs,proto3" json:"sent_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPing) Reset() {
	*x = MsgPing{}
	mi := &file_pb_v1_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPing) ProtoMessage() {}

func (x *MsgPing) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPing.ProtoReflect.Descriptor instead.
func (*MsgPing) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *MsgPing) GetSentTs() int64 {
	if x != nil {
		return x.SentTs
	}
	return 0
}

// Pong message.
type MsgPong struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The epoch millisecond timestamp when the message was sent.
	// Used to measure latency.
	SentTs        int64 `protobuf:"varint,1,opt,name=sent_ts,json=sentTs,proto3" json:"sent_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPong) Reset() {
	*x = MsgPong{}
	mi := &file_pb_v1_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPong) ProtoMessage() {}

func (x *MsgPong) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPong.ProtoReflect.Descriptor instead.
func (*MsgPong) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *MsgPong) GetSentTs() int64 {
	if x != nil {
		return x.SentTs
	}
	return 0
}

// Acknowledgement message.
// Empty.
type MsgAcknowledged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAcknowledged) Reset() {
	*x = MsgAcknowledged{}
	mi := &file_pb_v1_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAcknowledged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAcknowledged) ProtoMessage() {}

func (x *MsgAcknowledged) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAcknowledged.ProtoReflect.Descriptor instead.
func (*MsgAcknowledged) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{2}
}

// An error, usually sent by the server.
type MsgError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The error type.
	Type ErrType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.v1.ErrType" json:"type,omitempty"`
	// The error message (optional).
	Message       *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgError) Reset() {
	*x = MsgError{}
	mi := &file_pb_v1_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgError) ProtoMessage() {}

func (x *MsgError) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgError.ProtoReflect.Descriptor instead.
func (*MsgError) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *MsgError) GetType() ErrType {
	if x != nil {
		return x.Type
	}
	return ErrType_ERR_TYPE_UNSPECIFIED
}

func (x *MsgError) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// A protocol version.
type ProtoVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The minor protocol version.
	// Major protocol versions can be considered complete overhauls or changes to the underlying message header format.
	Major uint32 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	// The minor protocol version.
	// Minor protocol versions include breaking changes, but many parts of the protocol will remain the same between versions.
	Minor uint32 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	// The patch protocol version.
	// Patch protocol versions may include some trivial small additions, but nothing breaking.
	Patch         uint32 `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoVersion) Reset() {
	*x = ProtoVersion{}
	mi := &file_pb_v1_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoVersion) ProtoMessage() {}

func (x *ProtoVersion) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoVersion.ProtoReflect.Descriptor instead.
func (*ProtoVersion) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *ProtoVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ProtoVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *ProtoVersion) GetPatch() uint32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

// Client protocol negotiation.
type MsgVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The client's protocol version.
	Version       *ProtoVersion `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgVersion) Reset() {
	*x = MsgVersion{}
	mi := &file_pb_v1_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgVersion) ProtoMessage() {}

func (x *MsgVersion) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgVersion.ProtoReflect.Descriptor instead.
func (*MsgVersion) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *MsgVersion) GetVersion() *ProtoVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

// Message sent by the server as a reply to PROTO_VERSION.
// If a client receives this message, it may continue the handshake process.
type MsgVersionAccepted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server's protocol version.
	Version       *ProtoVersion `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgVersionAccepted) Reset() {
	*x = MsgVersionAccepted{}
	mi := &file_pb_v1_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgVersionAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgVersionAccepted) ProtoMessage() {}

func (x *MsgVersionAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgVersionAccepted.ProtoReflect.Descriptor instead.
func (*MsgVersionAccepted) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *MsgVersionAccepted) GetVersion() *ProtoVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

// Message sent by the server as a reply to PROTO_VERSION.
// If a client receives this message, it will be disconnected and must connect with a suitable version.
type MsgVersionRejected struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server's protocol version.
	Version *ProtoVersion `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// The reason the client's version was rejected.
	Reason VersionRejectionReason `protobuf:"varint,2,opt,name=reason,proto3,enum=pb.v1.VersionRejectionReason" json:"reason,omitempty"`
	// A message accompanying the rejection (optional).
	Message       *string `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgVersionRejected) Reset() {
	*x = MsgVersionRejected{}
	mi := &file_pb_v1_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgVersionRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgVersionRejected) ProtoMessage() {}

func (x *MsgVersionRejected) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgVersionRejected.ProtoReflect.Descriptor instead.
func (*MsgVersionRejected) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *MsgVersionRejected) GetVersion() *ProtoVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *MsgVersionRejected) GetReason() VersionRejectionReason {
	if x != nil {
		return x.Reason
	}
	return VersionRejectionReason_VERSION_REJECTION_REASON_UNSPECIFIED
}

func (x *MsgVersionRejected) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// Client authentication.
// Should be the first message sent to the server immediately upon connection.
// It will be replied to with either PROTO_AUTH_ACCEPTED or PROTO_AUTH_REJECTED.
type MsgAuthenticate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The room the user is trying to authenticate with.
	Room string `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	// The user's username.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// The user's password.
	Password      string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAuthenticate) Reset() {
	*x = MsgAuthenticate{}
	mi := &file_pb_v1_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAuthenticate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAuthenticate) ProtoMessage() {}

func (x *MsgAuthenticate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAuthenticate.ProtoReflect.Descriptor instead.
func (*MsgAuthenticate) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *MsgAuthenticate) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *MsgAuthenticate) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MsgAuthenticate) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Message sent by the server as a reply to PROTO_AUTHENTICATE.
// If a client receives this message, it is considered to be authenticated and connected, and a session has been established.
type MsgAuthAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAuthAccepted) Reset() {
	*x = MsgAuthAccepted{}
	mi := &file_pb_v1_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAuthAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAuthAccepted) ProtoMessage() {}

func (x *MsgAuthAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAuthAccepted.ProtoReflect.Descriptor instead.
func (*MsgAuthAccepted) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{9}
}

// Message sent by the server as a reply to PROTO_AUTHENTICATE.
// The client will be disconnected after receiving this message.
type MsgAuthRejected struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The reason the client's authentication request was rejected.
	Reason AuthRejectionReason `protobuf:"varint,1,opt,name=reason,proto3,enum=pb.v1.AuthRejectionReason" json:"reason,omitempty"`
	// A message accompanying the rejection (optional).
	Message       *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAuthRejected) Reset() {
	*x = MsgAuthRejected{}
	mi := &file_pb_v1_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAuthRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAuthRejected) ProtoMessage() {}

func (x *MsgAuthRejected) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAuthRejected.ProtoReflect.Descriptor instead.
func (*MsgAuthRejected) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *MsgAuthRejected) GetReason() AuthRejectionReason {
	if x != nil {
		return x.Reason
	}
	return AuthRejectionReason_AUTH_REJECTION_REASON_UNSPECIFIED
}

func (x *MsgAuthRejected) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// See MSG_TYPE_OPEN_OUTBOUND_PROXY.
type MsgOpenOutboundProxy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target peer's username.
	TargetUsername string `protobuf:"bytes,1,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgOpenOutboundProxy) Reset() {
	*x = MsgOpenOutboundProxy{}
	mi := &file_pb_v1_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgOpenOutboundProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgOpenOutboundProxy) ProtoMessage() {}

func (x *MsgOpenOutboundProxy) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgOpenOutboundProxy.ProtoReflect.Descriptor instead.
func (*MsgOpenOutboundProxy) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *MsgOpenOutboundProxy) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

// See MSG_TYPE_INBOUND_PROXY.
type MsgInboundProxy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The origin peer's username.
	OriginUsername string `protobuf:"bytes,1,opt,name=origin_username,json=originUsername,proto3" json:"origin_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgInboundProxy) Reset() {
	*x = MsgInboundProxy{}
	mi := &file_pb_v1_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgInboundProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInboundProxy) ProtoMessage() {}

func (x *MsgInboundProxy) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInboundProxy.ProtoReflect.Descriptor instead.
func (*MsgInboundProxy) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *MsgInboundProxy) GetOriginUsername() string {
	if x != nil {
		return x.OriginUsername
	}
	return ""
}

// See MSG_TYPE_GET_DIR_FILES.
type MsgGetDirFiles struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path of the directory within the share.
	// The path must begin with a `/`.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgGetDirFiles) Reset() {
	*x = MsgGetDirFiles{}
	mi := &file_pb_v1_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgGetDirFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetDirFiles) ProtoMessage() {}

func (x *MsgGetDirFiles) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetDirFiles.ProtoReflect.Descriptor instead.
func (*MsgGetDirFiles) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *MsgGetDirFiles) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// See MSG_TYPE_DIR_FILES.
type MsgDirFiles struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A non-exhaustive list of files within a directory.
	Files         []*MsgFileMeta `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDirFiles) Reset() {
	*x = MsgDirFiles{}
	mi := &file_pb_v1_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDirFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDirFiles) ProtoMessage() {}

func (x *MsgDirFiles) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDirFiles.ProtoReflect.Descriptor instead.
func (*MsgDirFiles) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *MsgDirFiles) GetFiles() []*MsgFileMeta {
	if x != nil {
		return x.Files
	}
	return nil
}

// See MSG_TYPE_GET_FILE_META.
type MsgGetFileMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path to the file.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgGetFileMeta) Reset() {
	*x = MsgGetFileMeta{}
	mi := &file_pb_v1_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgGetFileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetFileMeta) ProtoMessage() {}

func (x *MsgGetFileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetFileMeta.ProtoReflect.Descriptor instead.
func (*MsgGetFileMeta) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *MsgGetFileMeta) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// See MSG_TYPE_FILE_META.
type MsgFileMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The file's name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether the file is a directory.
	IsDir bool `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	// The file's size, in bytes.
	// Always zero if the file is a folder.
	Size          uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgFileMeta) Reset() {
	*x = MsgFileMeta{}
	mi := &file_pb_v1_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgFileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFileMeta) ProtoMessage() {}

func (x *MsgFileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFileMeta.ProtoReflect.Descriptor instead.
func (*MsgFileMeta) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *MsgFileMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgFileMeta) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *MsgFileMeta) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// See MSG_TYPE_GET_FILE.
type MsgGetFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path to the file.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The offset into the file to read, in bytes.
	// Values above the file size will just result in no data being returned.
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// The limit of the file to read, in bytes.
	// Specify 0 for no limit.
	Limit         uint64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgGetFile) Reset() {
	*x = MsgGetFile{}
	mi := &file_pb_v1_protocol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgGetFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetFile) ProtoMessage() {}

func (x *MsgGetFile) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetFile.ProtoReflect.Descriptor instead.
func (*MsgGetFile) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{17}
}

func (x *MsgGetFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MsgGetFile) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MsgGetFile) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// See MSG_TYPE_GET_ONLINE_USERS.
type MsgGetOnlineUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgGetOnlineUsers) Reset() {
	*x = MsgGetOnlineUsers{}
	mi := &file_pb_v1_protocol_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgGetOnlineUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetOnlineUsers) ProtoMessage() {}

func (x *MsgGetOnlineUsers) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetOnlineUsers.ProtoReflect.Descriptor instead.
func (*MsgGetOnlineUsers) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{18}
}

// OnlineUserInfo is information about an online user.
type OnlineUserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's username.
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineUserInfo) Reset() {
	*x = OnlineUserInfo{}
	mi := &file_pb_v1_protocol_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUserInfo) ProtoMessage() {}

func (x *OnlineUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUserInfo.ProtoReflect.Descriptor instead.
func (*OnlineUserInfo) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{19}
}

func (x *OnlineUserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// See MSG_TYPE_ONLINE_USERS.
type MsgOnlineUsers struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of online users in the room and their statuses.
	Users         []*OnlineUserInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgOnlineUsers) Reset() {
	*x = MsgOnlineUsers{}
	mi := &file_pb_v1_protocol_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgOnlineUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgOnlineUsers) ProtoMessage() {}

func (x *MsgOnlineUsers) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgOnlineUsers.ProtoReflect.Descriptor instead.
func (*MsgOnlineUsers) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{20}
}

func (x *MsgOnlineUsers) GetUsers() []*OnlineUserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

// See MSG_TYPE_BYE.
type MsgBye struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBye) Reset() {
	*x = MsgBye{}
	mi := &file_pb_v1_protocol_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBye) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBye) ProtoMessage() {}

func (x *MsgBye) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_protocol_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBye.ProtoReflect.Descriptor instead.
func (*MsgBye) Descriptor() ([]byte, []int) {
	return file_pb_v1_protocol_proto_rawDescGZIP(), []int{21}
}

var File_pb_v1_protocol_proto protoreflect.FileDescriptor

const file_pb_v1_protocol_proto_rawDesc = "" +
	"\n" +
	"\x14pb/v1/protocol.proto\x12\x05pb.v1\"\"\n" +
	"\aMsgPing\x12\x17\n" +
	"\asent_ts\x18\x01 \x01(\x03R\x06sentTs\"\"\n" +
	"\aMsgPong\x12\x17\n" +
	"\asent_ts\x18\x01 \x01(\x03R\x06sentTs\"\x11\n" +
	"\x0fMsgAcknowledged\"Y\n" +
	"\bMsgError\x12\"\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0e.pb.v1.ErrTypeR\x04type\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"P\n" +
	"\fProtoVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\rR\x05patch\";\n" +
	"\n" +
	"MsgVersion\x12-\n" +
	"\aversion\x18\x01 \x01(\v2\x13.pb.v1.ProtoVersionR\aversion\"C\n" +
	"\x12MsgVersionAccepted\x12-\n" +
	"\aversion\x18\x01 \x01(\v2\x13.pb.v1.ProtoVersionR\aversion\"\xa5\x01\n" +
	"\x12MsgVersionRejected\x12-\n" +
	"\aversion\x18\x01 \x01(\v2\x13.pb.v1.ProtoVersionR\aversion\x125\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1d.pb.v1.VersionRejectionReasonR\x06reason\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"]\n" +
	"\x0fMsgAuthenticate\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x11\n" +
	"\x0fMsgAuthAccepted\"p\n" +
	"\x0fMsgAuthRejected\x122\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x1a.pb.v1.AuthRejectionReasonR\x06reason\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"?\n" +
	"\x14MsgOpenOutboundProxy\x12'\n" +
	"\x0ftarget_username\x18\x01 \x01(\tR\x0etargetUsername\":\n" +
	"\x0fMsgInboundProxy\x12'\n" +
	"\x0forigin_username\x18\x01 \x01(\tR\x0eoriginUsername\"$\n" +
	"\x0eMsgGetDirFiles\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"7\n" +
	"\vMsgDirFiles\x12(\n" +
	"\x05files\x18\x01 \x03(\v2\x12.pb.v1.MsgFileMetaR\x05files\"$\n" +
	"\x0eMsgGetFileMeta\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"L\n" +
	"\vMsgFileMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"N\n" +
	"\n" +
	"MsgGetFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\"\x13\n" +
	"\x11MsgGetOnlineUsers\",\n" +
	"\x0eOnlineUserInfo\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"=\n" +
	"\x0eMsgOnlineUsers\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.pb.v1.OnlineUserInfoR\x05users\"\b\n" +
	"\x06MsgBye*\xa8\x04\n" +
	"\aMsgType\x12\x18\n" +
	"\x14MSG_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMSG_TYPE_PING\x10\x01\x12\x11\n" +
	"\rMSG_TYPE_PONG\x10\x02\x12\x19\n" +
	"\x15MSG_TYPE_ACKNOWLEDGED\x10\x03\x12\x12\n" +
	"\x0eMSG_TYPE_ERROR\x10\x04\x12\x14\n" +
	"\x10MSG_TYPE_VERSION\x10\x05\x12\x1d\n" +
	"\x19MSG_TYPE_VERSION_ACCEPTED\x10\x06\x12\x1d\n" +
	"\x19MSG_TYPE_VERSION_REJECTED\x10\a\x12\x19\n" +
	"\x15MSG_TYPE_AUTHENTICATE\x10\b\x12\x1a\n" +
	"\x16MSG_TYPE_AUTH_ACCEPTED\x10\t\x12\x1a\n" +
	"\x16MSG_TYPE_AUTH_REJECTED\x10\n" +
	"\x12 \n" +
	"\x1cMSG_TYPE_OPEN_OUTBOUND_PROXY\x10\v\x12\x1a\n" +
	"\x16MSG_TYPE_INBOUND_PROXY\x10\f\x12\x1a\n" +
	"\x16MSG_TYPE_GET_DIR_FILES\x10\r\x12\x16\n" +
	"\x12MSG_TYPE_DIR_FILES\x10\x0e\x12\x1a\n" +
	"\x16MSG_TYPE_GET_FILE_META\x10\x0f\x12\x16\n" +
	"\x12MSG_TYPE_FILE_META\x10\x10\x12\x15\n" +
	"\x11MSG_TYPE_GET_FILE\x10\x11\x12\x1d\n" +
	"\x19MSG_TYPE_GET_ONLINE_USERS\x10\x12\x12\x19\n" +
	"\x15MSG_TYPE_ONLINE_USERS\x10\x13\x12\x10\n" +
	"\fMSG_TYPE_BYE\x10\x14*\xeb\x02\n" +
	"\aErrType\x12\x18\n" +
	"\x14ERR_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ERR_TYPE_INTERNAL\x10\x01\x12\x1e\n" +
	"\x1aERR_TYPE_MALFORMED_MESSAGE\x10\x02\x12\x1e\n" +
	"\x1aERR_TYPE_PAYLOAD_TOO_LARGE\x10\x03\x12\x1b\n" +
	"\x17ERR_TYPE_MISSING_FIELDS\x10\x04\x12\x1b\n" +
	"\x17ERR_TYPE_INVALID_FIELDS\x10\x05\x12 \n" +
	"\x1cERR_TYPE_UNEXPECTED_MSG_TYPE\x10\x06\x12\x19\n" +
	"\x15ERR_TYPE_RATE_LIMITED\x10\a\x12\x1b\n" +
	"\x17ERR_TYPE_FILE_NOT_EXIST\x10\b\x12\x1a\n" +
	"\x16ERR_TYPE_UNIMPLEMENTED\x10\t\x12\x1e\n" +
	"\x1aERR_TYPE_PERMISSION_DENIED\x10\n" +
	"\x12\x1f\n" +
	"\x1bERR_TYPE_PATH_NOT_DIRECTORY\x10\v*\x8e\x01\n" +
	"\x16VersionRejectionReason\x12(\n" +
	"$VERSION_REJECTION_REASON_UNSPECIFIED\x10\x00\x12$\n" +
	" VERSION_REJECTION_REASON_TOO_OLD\x10\x02\x12$\n" +
	" VERSION_REJECTION_REASON_TOO_NEW\x10\x03*\x8d\x01\n" +
	"\x13AuthRejectionReason\x12%\n" +
	"!AUTH_REJECTION_REASON_UNSPECIFIED\x10\x00\x12-\n" +
	")AUTH_REJECTION_REASON_INVALID_CREDENTIALS\x10\x02\x12 \n" +
	"\x1cAUTH_REJECTION_REASON_BANNED\x10\x03Br\n" +
	"\tcom.pb.v1B\rProtocolProtoP\x01Z!friendnet.org/protocol/pb/v1;pbv1\xa2\x02\x03PXX\xaa\x02\x05Pb.V1\xca\x02\x05Pb\\V1\xe2\x02\x11Pb\\V1\\GPBMetadata\xea\x02\x06Pb::V1b\x06proto3"

var (
	file_pb_v1_protocol_proto_rawDescOnce sync.Once
	file_pb_v1_protocol_proto_rawDescData []byte
)

func file_pb_v1_protocol_proto_rawDescGZIP() []byte {
	file_pb_v1_protocol_proto_rawDescOnce.Do(func() {
		file_pb_v1_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_v1_protocol_proto_rawDesc), len(file_pb_v1_protocol_proto_rawDesc)))
	})
	return file_pb_v1_protocol_proto_rawDescData
}

var file_pb_v1_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pb_v1_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pb_v1_protocol_proto_goTypes = []any{
	(MsgType)(0),                 // 0: pb.v1.MsgType
	(ErrType)(0),                 // 1: pb.v1.ErrType
	(VersionRejectionReason)(0),  // 2: pb.v1.VersionRejectionReason
	(AuthRejectionReason)(0),     // 3: pb.v1.AuthRejectionReason
	(*MsgPing)(nil),              // 4: pb.v1.MsgPing
	(*MsgPong)(nil),              // 5: pb.v1.MsgPong
	(*MsgAcknowledged)(nil),      // 6: pb.v1.MsgAcknowledged
	(*MsgError)(nil),             // 7: pb.v1.MsgError
	(*ProtoVersion)(nil),         // 8: pb.v1.ProtoVersion
	(*MsgVersion)(nil),           // 9: pb.v1.MsgVersion
	(*MsgVersionAccepted)(nil),   // 10: pb.v1.MsgVersionAccepted
	(*MsgVersionRejected)(nil),   // 11: pb.v1.MsgVersionRejected
	(*MsgAuthenticate)(nil),      // 12: pb.v1.MsgAuthenticate
	(*MsgAuthAccepted)(nil),      // 13: pb.v1.MsgAuthAccepted
	(*MsgAuthRejected)(nil),      // 14: pb.v1.MsgAuthRejected
	(*MsgOpenOutboundProxy)(nil), // 15: pb.v1.MsgOpenOutboundProxy
	(*MsgInboundProxy)(nil),      // 16: pb.v1.MsgInboundProxy
	(*MsgGetDirFiles)(nil),       // 17: pb.v1.MsgGetDirFiles
	(*MsgDirFiles)(nil),          // 18: pb.v1.MsgDirFiles
	(*MsgGetFileMeta)(nil),       // 19: pb.v1.MsgGetFileMeta
	(*MsgFileMeta)(nil),          // 20: pb.v1.MsgFileMeta
	(*MsgGetFile)(nil),           // 21: pb.v1.MsgGetFile
	(*MsgGetOnlineUsers)(nil),    // 22: pb.v1.MsgGetOnlineUsers
	(*OnlineUserInfo)(nil),       // 23: pb.v1.OnlineUserInfo
	(*MsgOnlineUsers)(nil),       // 24: pb.v1.MsgOnlineUsers
	(*MsgBye)(nil),               // 25: pb.v1.MsgBye
}
var file_pb_v1_protocol_proto_depIdxs = []int32{
	1,  // 0: pb.v1.MsgError.type:type_name -> pb.v1.ErrType
	8,  // 1: pb.v1.MsgVersion.version:type_name -> pb.v1.ProtoVersion
	8,  // 2: pb.v1.MsgVersionAccepted.version:type_name -> pb.v1.ProtoVersion
	8,  // 3: pb.v1.MsgVersionRejected.version:type_name -> pb.v1.ProtoVersion
	2,  // 4: pb.v1.MsgVersionRejected.reason:type_name -> pb.v1.VersionRejectionReason
	3,  // 5: pb.v1.MsgAuthRejected.reason:type_name -> pb.v1.AuthRejectionReason
	20, // 6: pb.v1.MsgDirFiles.files:type_name -> pb.v1.MsgFileMeta
	23, // 7: pb.v1.MsgOnlineUsers.users:type_name -> pb.v1.OnlineUserInfo
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pb_v1_protocol_proto_init() }
func file_pb_v1_protocol_proto_init() {
	if File_pb_v1_protocol_proto != nil {
		return
	}
	file_pb_v1_protocol_proto_msgTypes[3].OneofWrappers = []any{}
	file_pb_v1_protocol_proto_msgTypes[7].OneofWrappers = []any{}
	file_pb_v1_protocol_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_v1_protocol_proto_rawDesc), len(file_pb_v1_protocol_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_v1_protocol_proto_goTypes,
		DependencyIndexes: file_pb_v1_protocol_proto_depIdxs,
		EnumInfos:         file_pb_v1_protocol_proto_enumTypes,
		MessageInfos:      file_pb_v1_protocol_proto_msgTypes,
	}.Build()
	File_pb_v1_protocol_proto = out.File
	file_pb_v1_protocol_proto_goTypes = nil
	file_pb_v1_protocol_proto_depIdxs = nil
}
